name = "ExistentialRules"
version = "0.1.0"
defaultTargets = ["ExistentialRules"]

[[lean_lib]]
name = "ExistentialRules"

[[require]]
name = "BasicLeanDatastructures"
git = "https://github.com/monsterkrampe/Basic-Lean-Datastructures.git"
rev = "main"

[[require]]
name = "PossiblyInfiniteTrees"
git = "https://github.com/monsterkrampe/Possibly-Infinite-Trees.git"
rev = "main"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "v4.21.0"

