name = "ExistentialRules"
version = "0.1.0"
defaultTargets = ["ExistentialRules"]

[[lean_lib]]
name = "ExistentialRules"

[[require]]
name = "BasicLeanDatastructures"
git = "https://github.com/monsterkrampe/Basic-Lean-Datastructures.git"
rev = "f7628a8f7d5498d93c10a2f3b15ec25870ef490f"

[[require]]
name = "PossiblyInfiniteTrees"
git = "https://github.com/monsterkrampe/Possibly-Infinite-Trees.git"
rev = "e9ebb3fc16759dff45d93fad87b0b611b357a916"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "v4.25.1"

[[require]]
name = "Canonical"
scope = "chasenorman"
rev = "v4.25.0"

